/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface": "#251818",
        "surface-container-high": "#fbe3e1",
        "on-background": "#251818",
        "primary-container": "#ff6b6b",
        "primary-fixed": "#ffdad8",
        "tertiary-fixed-dim": "#5adcb3",
        "inverse-on-surface": "#ffedeb",
        "on-primary-fixed": "#410006",
        "on-error-container": "#93000a",
        "inverse-surface": "#3b2d2c",
        "on-secondary-fixed-variant": "#713623",
        "background": "#f8f9ff",
        "on-tertiary-container": "#003b2c",
        "secondary-container": "#fdaa90",
        "primary": "#ae2f34",
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "outline": "#8c706f",
        "secondary": "#8d4d38",
        "gradient-end": "#7FFFD4",
        "on-tertiary-fixed": "#002117",
        "surface": "#ffffff",
        "surface-dim": "#ecd5d3",
        "tertiary-container": "#1aaf89",
        "on-secondary-container": "#783c28",
        "error": "#ba1a1a",
        "surface-variant": "#f5dddb",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#79f9ce",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#ffb59e",
        "surface-tint": "#ae2f34",
        "on-secondary-fixed": "#390c01",
        "gradient-mid": "#FFAB91",
        "on-primary-container": "#6d0010",
        "on-surface-variant": "#584140",
        "surface-container": "#ffe9e7",
        "button-gradient-pink": "#FF8E99",
        "button-gradient-coral": "#FF6B6B",
        "outline-variant": "#e0bfbd",
        "on-primary-fixed-variant": "#8c1520",
        "surface-container-low": "#fff0ef",
        "surface-bright": "#fff8f7",
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#ffb3b0",
        "tertiary": "#006c52",
        "primary-fixed-dim": "#ffb3b0",
        "secondary-fixed": "#ffdbd0",
        "gradient-start": "#FF6B6B",
        "on-tertiary-fixed-variant": "#00513d",
        "surface-container-highest": "#f5dddb",
        "on-error": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "13": "3.25rem",
      },
      fontFamily: {
        "sans": ["Inter", "system-ui", "-apple-system", "sans-serif"],
        "display": ["Poppins", "system-ui", "sans-serif"],
      },
      fontSize: {
        "label-lg": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "display-xl": ["60px", { lineHeight: "72px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
